# Generated by Django 4.2.11 on 2024-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatCrewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='conversation',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='character_image_url',
            field=models.URLField(default='demo.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='character_name',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='show_name',
            field=models.CharField(default='demo', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterConversation',
        ),
    ]
