# Generated by Django 4.2.11 on 2024-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatCrewApp', '0003_roleplaychathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplaychathistory',
            name='character_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleplaychathistory',
            name='opponent_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
