# Generated by Django 4.2.11 on 2024-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatCrewApp', '0006_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_message_count_characters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_message_count_roleplay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_message_date_characters',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_message_date_roleplay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
