# Generated by Django 4.2.11 on 2024-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatCrewApp', '0007_profile_daily_message_count_characters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_message_count_fanchat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_message_date_fanchat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
