# Generated by Django 4.2.11 on 2024-05-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatCrewApp', '0009_fanchathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanchathistory',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ChatCrewApp.fanchathistory'),
        ),
    ]
